config/routes.rb
Rails.application.routes.draw do
 class OnlyAjaxRequests
    def matches?(request)
      request.xhr?
    end
  end
  
 match '/ajax/getrws' => 'roadworks#rtrnjsonroadworks', :constraints => OnlyAjaxRequests.new, via: :get, defaults: {format: 'json'}
scope "(:locale)", locale: /en|nl/ do
  devise_for :users
  resources :roadworks
  resources :maps
  
  root 'roadworks#index'
  
  post '/roadworks/search' => 'roadworks#search'
  
 
  
 end
 
 

end

app/models/roadwork.rb
class Roadwork < ActiveRecord::Base

  def self.search(search)
    if search
      where('description LIKE ?', "%#{search}%")
    else
      all
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  
  before_action :set_locale
 
def set_locale
  I18n.locale = params[:locale] || I18n.default_locale #sets locale
end

def default_url_options(options = {})  #adds locale to url query string
  { locale: I18n.locale }.merge options #
end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
	before_filter :authenticate_user!
	def index
		
	end

end

app/controllers/roadworks_controller.rb
class RoadworksController < ApplicationController
  before_action :set_roadwork, only: [:show, :edit, :update, :destroy]

  # GET /roadworks
  # GET /roadworks.json
  def index
    @roadworks = Roadwork.all
  end

  # GET /roadworks/1
  # GET /roadworks/1.json
  def show
  end

  # GET /roadworks/new
  def new
    @roadwork = Roadwork.new
  end

  # GET /roadworks/1/edit
  def edit
  end

  # POST /roadworks
  # POST /roadworks.json
  def create
    @roadwork = Roadwork.new(roadwork_params)

    respond_to do |format|
      if @roadwork.save
        format.html { redirect_to @roadwork, notice: 'Roadwork was successfully created.' }
        format.json { render :show, status: :created, location: @roadwork }
      else
        format.html { render :new }
        format.json { render json: @roadwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roadworks/1
  # PATCH/PUT /roadworks/1.json
  def update
    respond_to do |format|
      if @roadwork.update(roadwork_params)
        format.html { redirect_to @roadwork, notice: 'Roadwork was successfully updated.' }
        format.json { render :show, status: :ok, location: @roadwork }
      else
        format.html { render :edit }
        format.json { render json: @roadwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roadworks/1
  # DELETE /roadworks/1.json
  def destroy
    @roadwork.destroy
    respond_to do |format|
      format.html { redirect_to roadworks_url, notice: 'Roadwork was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def search
    @roadworks = Roadwork.search(params[:key])
  end 
  
  def rtrnjsonroadworks
		render json: Roadwork.all #roadworks in db in json format
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roadwork
      @roadwork = Roadwork.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roadwork_params
      params.require(:roadwork).permit(:description, :startdate, :enddate, :latitude, :longitude, :tags, :submitteddate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/roadworks_helper.rb
module RoadworksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roadworks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default",>
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Roadworks in Aberdeen</a>
	  <% if user_signed_in? %>	
		<%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: 'btn btn-default navbar-btn'%>
		<%= link_to 'Roadworks Map', maps_path, class: 'btn btn-default navbar-btn' %>
	  <% else %>
		<%= link_to 'Login for Maps!', new_user_session_path, class: 'btn btn-default navbar-btn'%>
	  <%end%>
	  <form action ="/roadworks/search" method="post">
		<input name = "key" type="input" />
		<input value="Search" type="submit"/>
	  </form> 
    </div>
  </div>
</nav>

    <div id="main-container" class="container-fluid">
      <div class="row">
        <div class="col-xs-9">
          <%= yield %>
        </div>
      </div>
    </div>
    
    <nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <span class="navbar-text navbar-right">Roadworks in Aberdeen</span>
    <span class="navbar-text navbar-left">Updated: 16/07/2016</span>
  </div>
</nav>

</body>
</html>

app/views/maps/_map.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "gmaps.js" %>
<% end %>

<style>
html { height: 100% }
body { height: 100% }
#map-container { height: 30% }
</style>

<div id="map-wrapper">
	<div id="map-canvas"></div>
	<script>initialize();</script>
</div>

app/views/maps/index.html.erb
<%= render "map" %>

app/views/roadworks/_form.html.erb
<%= form_for(@roadwork) do |f| %>
  <% if @roadwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roadwork.errors.count, "error") %> prohibited this roadwork from being saved:</h2>

      <ul>
      <% @roadwork.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br>
    <%= f.text_field :startdate %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br>
    <%= f.text_field :enddate %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :submitteddate %><br>
    <%= f.text_field :submitteddate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roadworks/edit.html.erb
<h1>Editing Roadwork</h1>

<%= render 'form' %>

<%= link_to 'Show', @roadwork %> |
<%= link_to 'Back', roadworks_path %>

app/views/roadworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Current Roadworks in Aberdeen</h1>

<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr>
      <th>Description</th>
      <th>Start Date</th>
      <th>End Date</th>
    <!--  <th>Latitude</th> -->
     <!-- <th>Longitude</th> -->
      <th>Tags</th>
      <th>Submitted On</th>
      <!--<th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @roadworks.each do |roadwork| %>
      <tr>
        <td><%= roadwork.description %></td>
        <td><%= roadwork.startdate %></td>
        <td><%= roadwork.enddate %></td>
       <!-- <td><%= roadwork.latitude %></td> -->
       <!-- <td><%= roadwork.longitude %></td> -->
        <td><%= roadwork.tags %></td>
        <td><%= roadwork.submitteddate %></td>
        <% if current_user && current_user.admin?%>
        <td><%= link_to 'Show', roadwork, class: 'btn btn-link'%></td>
        <td><%= link_to 'Edit', edit_roadwork_path(roadwork) , class:'btn btn-link'%></td>
        <td><%= link_to 'Destroy', roadwork, method: :delete, data: { confirm: 'Are you sure?' } ,class: 'btn btn-danger'%></td>
		<%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roadwork', new_roadwork_path %>

app/views/roadworks/new.html.erb
<h1>New Roadwork</h1>

<%= render 'form' %>

<%= link_to 'Back', roadworks_path %>

app/views/roadworks/search.html.erb
<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr>
      <th>Description</th>
      <th>Start Date</th>
      <th>End Date</th>
    <!--  <th>Latitude</th> -->
     <!-- <th>Longitude</th> -->
      <th>Tags</th>
      <th>Submitted On</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roadworks.each do |roadwork| %>
      <tr>
        <td><%= roadwork.description %></td>
        <td><%= roadwork.startdate %></td>
        <td><%= roadwork.enddate %></td>
       <!-- <td><%= roadwork.latitude %></td> -->
       <!-- <td><%= roadwork.longitude %></td> -->
        <td><%= roadwork.tags %></td>
        <td><%= roadwork.submitteddate %></td>
        <td><%= link_to 'Show', roadwork, class: 'btn btn-link'%></td>
			<% if current_user && current_user.admin?%>
        <td><%= link_to 'Edit', edit_roadwork_path(roadwork) , class:'btn btn-link'%></td>
        <td><%= link_to 'Destroy', roadwork, method: :delete, data: { confirm: 'Are you sure?' } ,class: 'btn btn-danger'%></td>
			<%end%>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/roadworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @roadwork.description %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @roadwork.startdate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @roadwork.enddate %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @roadwork.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @roadwork.longitude %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @roadwork.tags %>
</p>

<p>
  <strong>Submitteddate:</strong>
  <%= @roadwork.submitteddate %>
</p>

<%= link_to 'Edit', edit_roadwork_path(@roadwork) %> |
<%= link_to 'Back', roadworks_path %>